#SPDX-License-Identifier: MIT-0
---
# tasks file for configuring mosquitto broker

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
- name: Change mosquitto configuration folder ownership
  ansible.builtin.file:
    path: "{{ mosquitto_conf_path }}"
    state: directory
    owner: mosquitto
    group: mosquitto
    recurse: true
  tags: permissions


# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
- name: Allow all mosquitto group members to read log
  ansible.builtin.file:
    path: "{{ mosquitto_logfile }}"
    owner: mosquitto
    group: mosquitto
    mode: 0640
  tags: permissions


# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
- name: Copy mosquitto logrotate file
  ansible.builtin.copy:
    src: "{{ role_path }}/files/mosquitto.logrotate"
    dest: "{{ mosquitto_logrotate_file }}"
    owner: root
    group: root
    mode: 0644
  tags: logrotate
  notify: Validate Mosquitto logrotate


# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
- name: Copy mosquitto service file
  ansible.builtin.copy:
    src: "{{ role_path }}/files/mosquitto.service"
    dest: "{{ mosquitto_service_file }}"
    owner: root
    group: root
    mode: 0644
  tags: service_file
  notify: Reload Mosquitto configurations


# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
- name: Copy mosquitto.conf file
  ansible.builtin.copy:
    src: "{{ role_path }}/files/mosquitto.conf"
    dest: "{{ mosquitto_conf_path }}/mosquitto.conf"
    owner: mosquitto
    group: mosquitto
    mode: 0644
  tags: mosquitto_conf
  notify: Hard reload Mosquitto


# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
- name: Copy CA file
  ansible.builtin.copy:
    src: "{{ role_path }}/files/ca.crt"
    dest: "{{ mosquitto_conf_path }}/ca_certificates/ca.crt"
    owner: mosquitto
    group: mosquitto
    mode: 0644
  tags: mosquitto_tls
  notify: Hard reload Mosquitto


# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
- name: Copy cert file
  ansible.builtin.copy:
    src: "{{ role_path }}/files/server.crt"
    dest: "{{ mosquitto_conf_path }}/certs/server.crt"
    owner: mosquitto
    group: mosquitto
    mode: 0644
  tags: mosquitto_tls
  notify: Hard reload Mosquitto


# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
- name: Copy server keyfile
  ansible.builtin.copy:
    src: "{{ role_path }}/files/server.key"
    dest: "{{ mosquitto_conf_path }}/certs/server.key"
    owner: mosquitto
    group: mosquitto
    mode: 0600
  tags: mosquitto_tls
  notify: Hard reload Mosquitto
