#SPDX-License-Identifier: MIT-0
---
# tasks file for configuring mosquitto broker

###################################################
# Mosquitto file locations                        #
# Database  /var/lib/mosquitto/mosquitto.db       #
# Logs      /var/log/mosquitto/mosquitto.log      #
# Config    /etc/mosquitto/mosquitto.conf         #
# Service   /lib/systemd/system/mosquitto.service #
###################################################

# check this site https://www.monotux.tech/posts/2022/01/mosquitto-systemd/

# copy service file

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
- name: Copy mosquitto logrotate file
  ansible.builtin.copy:
    src: "{{ role_path }}/files/mosquitto.logrotate"
    dest: /etc/logrotate.d/mosquitto
    owner: root
    group: root
    mode: 0644
  tags: logrotate
  notify: Validate Mosquitto logrotate

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
- name: Copy mosquitto.conf file
  ansible.builtin.copy:
    src: "{{ role_path }}/files/mosquitto.conf"
    dest: /etc/mosquitto/mosquitto.conf
    owner: root
    group: root
    mode: 0644
  tags: mosquitto_conf
  notify: Hard reload Mosquitto
