#SPDX-License-Identifier: MIT-0
---
# handlers file for postgres

###################################################
# Hard reload restarts and pics up config changes #
###################################################

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_service_module.html
- name: Hard reload PostgreSQL
  ansible.builtin.systemd_service:
    name: postgresql.service
    state: restarted
    daemon_reload: true
