#SPDX-License-Identifier: MIT-0
---
# tasks file for configuring PostgreSQL database

# https://docs.ansible.com/ansible/latest/collections/community/postgresql/postgresql_user_module.html
- name: Connect to default database and change postgres user's password
  community.postgresql.postgresql_user:
    db: postgres
    user: postgres
    password: "{{ lookup('ansible.builtin.env', 'PG_USER_PW') }}"
  environment:
    PGOPTIONS: "-c password_encryption=scram-sha-256"
  notify: Hard reload Mosquitto
  tags: configure_postgres

# TODO: Cannot change password due to Peer authentication failed for user \"postgres\"\n"
# --> maybe change in pg_hba.conf, (location: sudo -u postgres psql -c 'show hba_file')

# TODO: Create a db user other than default
# TODO: Create named schema/database for whatever domain the application is going to be (e.g. homeserver)
# TODO: Create a relational schema for the domain data model which consists of persisted messages