#SPDX-License-Identifier: MIT-0
---
# tasks file for platform

- name: Update and upgrade apt
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: yes

- name: Ensure users are created
  include_tasks: create-users.yaml