#SPDX-License-Identifier: MIT-0
---
# tasks file for updating system packages


# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
- name: Copy sources list
  ansible.builtin.copy:
    become: yes
    src: ./platform/files/sources.list
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644
  tags: update_system_packages

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
- name: Update and upgrade apt
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: yes
    install_recommends: true
  tags: update_system_packages
