#SPDX-License-Identifier: MIT-0
---
# tasks file for updating system packages


# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
- name: Copy sources list
  ansible.builtin.copy:
    src: "{{ role_path }}/files/sources.list"
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644
  tags: sources_list

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
- name: Update and upgrade apt
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: yes
  tags: apt_update
